### ISSUE TITLE
Test system doesn't build

### ISSUE THREAD

**Issue by quicklisp** [AccelerationNet/function-cache#6]
I get this:

    ; file: /home/quicklisp/quicklisp-controller/dist/build-cache/function-cache/7173aaa4e9e260108f1e3d2cab7a00327cacb9e1/function-cache-20181015-git/test/metering.lisp
    ; in: DEFCACHED (TEST-METERED :CACHE-CLASS (QUOTE METERED-CACHE))
    ;     (FUNCTION-CACHE:DEFCACHED (FUNCTION-CACHE-TEST::TEST-METERED :CACHE-CLASS
    ;                                'FUNCTION-CACHE-TEST::METERED-CACHE)
    ;         (FUNCTION-CACHE-TEST::A)
    ;       FUNCTION-CACHE-TEST::A)
    ; 
    ; caught ERROR:
    ;   (during macroexpansion of (DEFCACHED (TEST-METERED :CACHE-CLASS ...) ...))
    ;   The value A is not of type LIST
    Unhandled UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {10005305B3}>: COMPILE-FILE-ERROR while compiling #<CL-SOURCE-FILE "function-cache-test" "test" "metering">

**Comment by bobbysmith007** [comment]
Thanks for the report.  I have patched the issue and all tests load and pass again.
