### ISSUE TITLE
functions names

### ISSUE THREAD

**Issue by arademaker** [AccelerationNet/function-cache#7]
In SBCL, if I define a `(defcached foo ...)` and try to use the name `foo` in other functions in the same file, I got an `undefined variable`

**Comment by bobbysmith007** [comment]
Are you relatively new to common lisp?  CL is a lisp 2 defining a function will not define a variable.  You should be able to refer to function foo as `#'foo` , and you can call  it as `(foo ...)` or `(funcall #'foo ...)` or `(apply #'foo)`

Or perhaps something else is going on, but I have been using this code for about a decade and havent run into problems with basic usage in a long time.  I'll need more info to go off of

**Comment by bobbysmith007** [comment]
I think this is closed?
